// DataForSEO API base URL
export const DATAFORSEO_API_BASE = "https://api.dataforseo.com/v3";

// API endpoints
export const ENDPOINTS = {
  KEYWORD_SUGGESTIONS:
    "/dataforseo_labs/google/keyword_suggestions/live",
  KEYWORD_IDEAS:
    "/dataforseo_labs/google/keyword_ideas/live",
  KEYWORDS_FOR_KEYWORDS:
    "/keywords_data/google_ads/keywords_for_keywords/live",
} as const;

// Response character limit to avoid overwhelming MCP context
export const CHARACTER_LIMIT = 50_000;

// Default request limits per source (DataForSEO max is 1000 each)
export const DEFAULT_LIMIT_PER_SOURCE = 200;

// Known brand names — keywords that contain these (as whole words) are flagged as branded.
// The user can extend this list via the `exclude_brands` tool parameter.
export const BUILT_IN_BRANDS: string[] = [
  // Tech / software
  "google",
  "youtube",
  "facebook",
  "instagram",
  "twitter",
  "tiktok",
  "snapchat",
  "whatsapp",
  "telegram",
  "linkedin",
  "pinterest",
  "reddit",
  "twitch",
  "discord",
  "slack",
  "zoom",
  "teams",
  "skype",
  "microsoft",
  "windows",
  "office",
  "outlook",
  "onedrive",
  "sharepoint",
  "azure",
  "apple",
  "iphone",
  "ipad",
  "macbook",
  "imac",
  "itunes",
  "icloud",
  "siri",
  "amazon",
  "aws",
  "alexa",
  "kindle",
  "netflix",
  "spotify",
  "hulu",
  "disney",
  "hbo",
  "paramount",
  "peacock",
  "meta",
  "openai",
  "chatgpt",
  "gemini",
  "claude",
  "adobe",
  "photoshop",
  "illustrator",
  "premiere",
  "canva",
  "figma",
  "notion",
  "airtable",
  "trello",
  "asana",
  "jira",
  "hubspot",
  "salesforce",
  "shopify",
  "wordpress",
  "wix",
  "squarespace",
  "mailchimp",
  "paypal",
  "stripe",
  "square",
  "venmo",
  "coinbase",
  "binance",
  "ebay",
  "etsy",
  "alibaba",
  "aliexpress",
  "walmart",
  "target",
  "costco",
  "ikea",
  "wayfair",
  "uber",
  "lyft",
  "airbnb",
  "booking",
  "expedia",
  "tripadvisor",
  // Fashion / sports
  "nike",
  "adidas",
  "puma",
  "reebok",
  "newbalance",
  "underarmour",
  "lululemon",
  "zara",
  "hm",
  "uniqlo",
  "gucci",
  "prada",
  "chanel",
  "louis vuitton",
  "hermes",
  "rolex",
  "cartier",
  // Food / beverage
  "mcdonalds",
  "starbucks",
  "subway",
  "kfc",
  "chipotle",
  "dominos",
  "pizzahut",
  "dunkin",
  "coca-cola",
  "pepsi",
  "redbull",
  "monster",
  // Automotive
  "tesla",
  "ford",
  "chevrolet",
  "toyota",
  "honda",
  "bmw",
  "mercedes",
  "audi",
  "volkswagen",
  "hyundai",
  "kia",
  "nissan",
  // Other common brands
  "samsung",
  "sony",
  "lg",
  "panasonic",
  "philips",
  "bosch",
  "dyson",
  "roomba",
  "fitbit",
  "garmin",
];
